### ISSUE TITLE
Invalid kotlin-serialization-compiler-plugin-embeddable dependency

### ISSUE THREAD

**Issue by titivermeesch** [Sithira/FlutterRadioPlayer#101]
I recently tried to use the new v3 version of flutter_radio_player but when building the application I'm getting the following error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_radio_player:compileDebugKotlin'.
> Error while evaluating property 'filteredArgumentsMap' of task ':flutter_radio_player:compileDebugKotlin'
   > Could not resolve all files for configuration ':flutter_radio_player:kotlinCompilerPluginClasspathDebug'.
      > Could not find org.jetbrains.kotlin:kotlin-serialization-compiler-plugin-embeddable:1.7.10.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-serialization-compiler-plugin-embeddable/1.7.10/kotlin-serialization-compiler-plugin-embeddable-1.7.10.pom
          - https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-serialization-compiler-plugin-embeddable/1.7.10/kotlin-serialization-compiler-plugin-embeddable-1.7.10.pom
          - https://storage.googleapis.com/download.flutter.io/org/jetbrains/kotlin/kotlin-serialization-compiler-plugin-embeddable/1.7.10/kotlin-serialization-compiler-plugin-embeddable-1.7.10.pom
        Required by:
            project :flutter_radio_player

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
```

I see this dependency exists in maven central but is it possible the version used here is not being hosted by them anymore? I don't see 1.7.10 in maven repository

**Comment by titivermeesch** [comment]
Or maybe it's an issue with my setup, but I didn't have this issue on v2

**Comment by decemberLi** [comment]
same error. how did you solved it, bro ?

**Comment by titivermeesch** [comment]
> same error. how did you solved it, bro ?

I upgraded my graddle version and kotlin version inside one of the build.gradle files under `/android`

**Comment by Sithira** [comment]
@decemberLi if you were able to solve the error after upgrading the kotlin version like @titivermeesch mentioned let me know. i will add this to the docs

**Comment by aria1632** [comment]
same error... how did you fix? ...

**Comment by Sithira** [comment]
Leaving this here in case some one else in trouble https://github.com/Sithira/FlutterRadioPlayer/issues/105#issuecomment-2419830417

**Comment by maendamedia** [comment]
Same error here after updates on kotlin and gradle"

`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_radio_player:compileDebugKotlin'.
> Could not resolve all files for configuration ':flutter_radio_player:kotlinCompilerPluginClasspathDebug'.
   > Could not find org.jetbrains.kotlin:kotlin-serialization-compiler-plugin-embeddable:1.8.22.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-serialization-compiler-plugin-embeddable/1.8.22/kotlin-serialization-compiler-plugin-embeddable-1.8.22.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-serialization-compiler-plugin-embeddable/1.8.22/kotlin-serialization-compiler-plugin-embeddable-1.8.22.pom
       - https://storage.googleapis.com/download.flutter.io/org/jetbrains/kotlin/kotlin-serialization-compiler-plugin-embeddable/1.8.22/kotlin-serialization-compiler-plugin-embeddable-1.8.22.pom
     Required by:
         project :flutter_radio_player`
         
How to fix?
