### ISSUE TITLE
`jumpToSourceIndex` function is missed 

### ISSUE THREAD

**Issue by bossly** [Sithira/FlutterRadioPlayer#103]
![Screenshot 2024-10-14 at 23 41 57](https://github.com/user-attachments/assets/b94dc4f1-fd8c-4053-b97d-ec2508fc91a4)

Function is missed

**Comment by Sithira** [comment]
@bossly this is fixed in 3.0.1. Thanks for pointing it out 👍 

make sure you star the repo if it worked
