### ISSUE TITLE
i dont know how can i fix this issue

### ISSUE THREAD

**Issue by aria1632** [Sithira/FlutterRadioPlayer#105]
hi

I hope you dont mind, but I wanted to let you know that I am not fluent in english as I am from korea. thank you for your understandning.

to get to the point, I am encountering the following error during the build process

===========================================================

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_radio_player:compileDebugKotlin'.
> Could not resolve all files for configuration ':flutter_radio_player:kotlinCompilerPluginClasspathDebug'.
   > Could not find org.jetbrains.kotlin:kotlin-serialization-compiler-plugin-embeddable:1.8.22.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-serialization-compiler-plugin-embeddable/1.8.22/kotlin-serialization-compiler-plugin-embeddable-1.8.22.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-serialization-compiler-plugin-embeddable/1.8.22/kotlin-serialization-compiler-plugin-embeddable-1.8.22.pom
       - https://storage.googleapis.com/download.flutter.io/org/jetbrains/kotlin/kotlin-serialization-compiler-plugin-embeddable/1.8.22/kotlin-serialization-compiler-plugin-embeddable-1.8.22.pom
     Required by:
         project :flutter_radio_player

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 4s
Error: Gradle task assembleDebug failed with exit code 1

============================================================

could you please let me know what might be causing this issue? I would greatly appreciate any advice or guidance you can provide.

thank you for your help

(i am using version 3.0.1.)

**Comment by Sithira** [comment]
@aria1632 you need to update your gradle version in your app to the latest one. 
[Example gradle.build](https://github.com/Sithira/FlutterRadioPlayer/blob/master/example/android/build.gradle)
