### ISSUE TITLE
Error When i added and build

### ISSUE THREAD

**Issue by sumithkrishnank** [Sithira/FlutterRadioPlayer#108]
Note: /Users/sumithkrishnank/.pub-cache/hosted/pub.dev/android_intent_plus-5.2.0/android/src/main/java/dev/fluttercommunity/plus/androidintent/MethodCallHandlerImpl.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_radio_player:compileReleaseKotlin'.
> Error while evaluating property 'filteredArgumentsMap' of task ':flutter_radio_player:compileReleaseKotlin'.
   > Could not resolve all files for configuration ':flutter_radio_player:kotlinCompilerPluginClasspathRelease'.
      > Could not find org.jetbrains.kotlin:kotlin-serialization-compiler-plugin-embeddable:1.7.10.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-serialization-compiler-plugin-embeddable/1.7.10/kotlin-serialization-compiler-plugin-embeddable-1.7.10.pom
          - https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-serialization-compiler-plugin-embeddable/1.7.10/kotlin-serialization-compiler-plugin-embeddable-1.7.10.pom
          - https://storage.googleapis.com/download.flutter.io/org/jetbrains/kotlin/kotlin-serialization-compiler-plugin-embeddable/1.7.10/kotlin-serialization-compiler-plugin-embeddable-1.7.10.pom
          - https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-serialization-compiler-plugin-embeddable/1.7.10/kotlin-serialization-compiler-plugin-embeddable-1.7.10.pom
        Required by:
            project :flutter_radio_player. when i try to add   flutter_radio_player: ^3.0.2.    please tell what is this error. when i added in pubspec.yaml and tried to build.

**Comment by Sithira** [comment]
Please update your Kotlin version to latest version 🙂

**Comment by sumithkrishnank** [comment]
let me check.

**Comment by sumithkrishnank** [comment]
its working now. but have buffering issue. when interruptions coming the player is buffering. live radio should not buffer. to avoid buffering what we can do ?

**Comment by Sithira** [comment]
You should check with your internet connection or your streaming server. There is nothing much this plugin can do for you. Im sorry :-(
