### ISSUE TITLE
Radio is Buffering. No need of Buffering . what to do

### ISSUE THREAD

**Issue by sumithkrishnank** [Sithira/FlutterRadioPlayer#109]
its working now. but have buffering issue. when interruptions coming the player is buffering. live radio should not buffer. to avoid buffering what we can do ?

**Comment by sumithkrishnank** [comment]
i am using  flutter_radio_player: ^2.0.3 . in this do we have any option to avoid buffering ?

**Comment by Sithira** [comment]
Im afraid no, there is nothing offered in this plugin or any plugin out there that could avoid buffering. Buffering is based on your internet connection and streaming server

**Comment by sumithkrishnank** [comment]
my doubt is interruptions like calls and other media play. after call coming the player is starting from buffered position.
