### ISSUE TITLE
Radio play Buffering after calls

### ISSUE THREAD

**Issue by sumithkrishnank** [Sithira/FlutterRadioPlayer#110]
my doubt is interruptions like calls and other media play. after call coming the player is starting from buffered position.

**Comment by Sithira** [comment]
i believe that is the default behavior in both IOS and Android, it buffers in the background and then resumes. However you can see seek buttons in the media controls if it ever buffers

**Comment by sumithkrishnank** [comment]
my doubt . Is there any option to find the interruption like calls and media play in the player. is there any inbuilt methods ? . because if we use audio session that will not work because the players default behaviour already have interuption handling and pause . so is there any default methods that can use to find how interruption coming and how pause operation is causing .

**Comment by Sithira** [comment]
Im afraid there are no inbuilt methods. Interruptions are handled by media3
which is the android system

**Comment by sumithkrishnank** [comment]
ok. thanks for the information.
