### ISSUE TITLE
Bug: Play/pause button first start

### ISSUE THREAD

**Issue by sarp86** [Sithira/FlutterRadioPlayer#14]
Only at the first start of the radio, the status of the button is play but should be paused. Music is playing and show play button. 

After press on play button the status of the button get correct. 

Tested with: ios iphone X 13.3.1

**Comment by srkraut** [comment]
I am also having this issue , any workaround ?

**Comment by Sithira** [comment]
ill look into this.

**Comment by sarp86** [comment]
@Sithira How long it will take for new update? Thanks

**Comment by Sithira** [comment]
I have tested on iOS 13.2.1 and it works fine. Can you show me how you configured the plugin init ?

**Comment by sarp86** [comment]
I try the your example from github **FlutterRadioPlayer/example/lib/** and the problem with the play button still exists (iOS).

**Comment by sarp86** [comment]
I forget one code line: await flutterRadioPlayer.playOrPause(); 
now its working correctly and play/pause state change correctly
