### ISSUE TITLE
Problems in iOS

### ISSUE THREAD

**Issue by mkdirmatias** [Sithira/FlutterRadioPlayer#16]
Hi, I've been testing the plugin and I loved it, on Android it works perfectly, but on iOS I found a couple of drawbacks. I'll explain my case.

I have an app, with two views one called Home (which would be the screen you see when you start the app) and one called Radio (this is where I implement the plugins). Then from Home I can enter to the radio (I do this because the app has more functionalities from which you can access from Home).

The first inconvenience is that if from Home I enter to Radio and then I return to Home and then I enter again to Radio, the app closes immediately.

The error is generated in the following code:

![](https://i.imgur.com/5e1KU7F.png)

and the console displays the following:

![](https://i.imgur.com/GFPgXMq.png)

in general, I could solve it saving the reproduction state in the Storage of the device, because when I enter to Radio for the second time, the following code is executed again and there the error is generated:

```
await _reproductor.init("title", "description","URL", "false");
```

Then, when I have the status of "started" the transmission, I avoid that code to be executed again, and when I do that, the plugins works again well.

The next problem I found is in the second plan playback. If the app is open in Radio, the controls in background work correctly, but if the app is in Home, the controls don't work, and when I put play/pause the app closes giving the same error as above.

I tested it on an iPhone 7 with iOS 13.5.5 and an iPhone 11 pro Max with iOS 13.5,

Greetings.

**Comment by Sithira** [comment]
ill look into this soon   👍

**Comment by Sithira** [comment]
Should be fixed by the new update

**Comment by Ponraj-Paulraj** [comment]
@Sithira , Seems like the fix is available on "dev" branch and not reached "Master". Can you please release a new version with the fix?
