### ISSUE TITLE
Another SimpleCache instance uses the folder:

### ISSUE THREAD

**Issue by CedenoH07** [Sithira/FlutterRadioPlayer#17]
I'm having the following error in multiple devices isn't all the time but is crashing the app, it looks like it is something to do with SimpleExoPlayer caching process but I would like to see if you are familiar with this? and if can ve resolve from the library point of view. 

Fatal Exception: java.lang.RuntimeException
Unable to start service me.sithiramunasinghe.flutter.flutter_radio_player.core.Streaming
Core@f008310 with Intent { cmp=com.tex.app/me.sithiramunasinghe.flutter.flutter_radio_player.core.StreamingCore (has extras) }: java.lang.IllegalStateException: Another SimpleCache instance uses the folder: /data/user/0/com.test.app/cache

<img width="709" alt="Screen Shot 2020-06-21 at 7 36 39 PM" src="https://user-images.githubusercontent.com/20801408/85237658-88670100-b3f6-11ea-901a-487c38c52475.png">

Thanks!.

**Comment by Sithira** [comment]
I think this is an ExoPlayer issue. This plugin just uses a basic setup of ExoPlayer to avoid any complications.
