### ISSUE TITLE
Error in Service

### ISSUE THREAD

**Issue by fabiopratta** [Sithira/FlutterRadioPlayer#18]
/MethodChannel#flutter_radio_player(24427): Failed to handle method call
E/MethodChannel#flutter_radio_player(24427): java.lang.IllegalArgumentException: Service not registered: me.sithiramunasinghe.flutter.flutter_radio_player.FlutterRadioPlayerPlugin$serviceConnection$1@94492bd
E/MethodChannel#flutter_radio_player(24427): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1160)
E/MethodChannel#flutter_radio_player(24427): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1475)
E/MethodChannel#flutter_radio_player(24427): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:644)
E/MethodChannel#flutter_radio_player(24427): 	at me.sithiramunasinghe.flutter.flutter_radio_player.FlutterRadioPlayerPlugin.stop(FlutterRadioPlayerPlugin.kt:181)
E/MethodChannel#flutter_radio_player(24427): 	at me.sithiramunasinghe.flutter.flutter_radio_player.FlutterRadioPlayerPlugin.onMethodCall(FlutterRadioPlayerPlugin.kt:75)
E/MethodChannel#flutter_radio_player(24427): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#flutter_radio_player(24427): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter_radio_player(24427): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/MethodChannel#flutter_radio_player(24427): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_radio_player(24427): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#flutter_radio_player(24427): 	at android.os.Looper.loop(Looper.java:135)
E/MethodChannel#flutter_radio_player(24427): 	at android.app.ActivityThread.main(ActivityThread.java:7325)
E/MethodChannel#flutter_radio_player(24427): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_radio_player(24427): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
E/MethodChannel#flutter_radio_player(24427): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by Sithira** [comment]
Are you calling the lib as provided in the example ?

**Comment by fabiopratta** [comment]
Hi, yes...

My pubspec.yaml 

`  #Firebase
  flutter_local_notifications:
  firebase_analytics: any
  firebase_messaging: 6.0.9
  firebase_core: ^0.4.0
  cached_network_image: 
  mask_text_input_formatter: ^1.0.7  
  localstorage: ^3.0.0
  minimize_app:
  #Radio
  flutter_radio_player: ^1.0.4`

My android manifest

`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="br.com.radio_brotense">
    
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="Rádio Brotense"
        android:icon="@mipmap/launcher_icon"
        android:networkSecurityConfig="@xml/network_security_config"
        android:usesCleartextTraffic="true">
        
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
            
        </activity>
        
        <service
            android:name="live.exit.musicplayer.MusicPlayerService"
            android:enabled="true" />

            <service 
            android:name=".core.StreamingCore" 
            android:enabled="true" />

        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
   
</manifest>
`

and my home is this example https://pub.dev/packages/flutter_radio_player#-example-tab-

tês

**Comment by Sithira** [comment]
Should be fixed by the new update
