### ISSUE TITLE
In android 9 the notification does not close when the app closes.

### ISSUE THREAD

**Issue by cjamcu** [Sithira/FlutterRadioPlayer#21]
I have noticed that in android 9 when the app is closed the music continues to run since the notification is still open.

**Comment by Sithira** [comment]
Hi, @cjamcu that's the default behavior of ExoPlayer on a Foreground service. You should stop the player manually by the notification bar. 

What is your point of view?

**Comment by cjamcu** [comment]
When users close the application, the notification must be removed and thus the Foreground service stops. In versions lower than Android 9 if it has this behavior.

**Comment by Sithira** [comment]
I think this is doable with a Flutter life-cycle event. It's just a matter of calling the StreamingCore's `stop` method. That will detach the notification making the foreground service stop

**Comment by afkcodes** [comment]
how can we add metas for notification ? like images and track metadata ? @Sithira @cjamcu

**Comment by Sithira** [comment]
> how can we add metas for notification? like images and track metadata ? @Sithira @cjamcu

You mean like dynamic content? Dynamic images?

**Comment by JanStorm** [comment]
@cjamcu idk if this is the problem you were facing, but the foreground service should definitely stop when the app gets destroyed. Like in Android when i remove app from "recent apps" list. is this the problem you mentioned?

**Comment by Sithira** [comment]
Has been updated to v2. Please check the master branch
