### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by glin94** [Sithira/FlutterRadioPlayer#25]
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /Users/linar/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_radio_player-1.0.5/ios/Classes/SwiftFlutterRadioPlayerPlugin.swift, line 109

**Comment by Sithira** [comment]
Which version are you using ?

**Comment by glin94** [comment]
> Which version are you using ?
1.0.5

**Comment by Sithira** [comment]
> > Which version are you using ?
> > 1.0.5

The package has been updated. Kindly update your version to the latest

**Comment by Sithira** [comment]
Has been updated to v2. Please check the master branch
