### ISSUE TITLE
I'm facing this error and can you help me something what was wrong?

### ISSUE THREAD

**Issue by zarnimoehtet** [Sithira/FlutterRadioPlayer#31]
D/AndroidRuntime(31948): Shutting down VM
E/AndroidRuntime(31948): FATAL EXCEPTION: main
E/AndroidRuntime(31948): Process: com.nwt.shwe_fm, PID: 31948
E/AndroidRuntime(31948): java.lang.NoSuchMethodError: No static method getLooper()Landroid/os/Looper; in class Lc/c/a/b/j2/j0; or its super classes (declaration of 'c.c.a.b.j2.j0' appears in /data/app/com.nwt.shwe_fm-2/base.apk)
E/AndroidRuntime(31948): 	at c.c.a.b.b2.a.a.<init>(:453)
E/AndroidRuntime(31948): 	at me.sithiramunasinghe.flutter.flutter_radio_player.core.StreamingCore.onStartCommand(:210)
E/AndroidRuntime(31948): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3043)
E/AndroidRuntime(31948): 	at android.app.ActivityThread.access$2300(ActivityThread.java:153)
E/AndroidRuntime(31948): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
E/AndroidRuntime(31948): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(31948): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(31948): 	at android.app.ActivityThread.main(ActivityThread.java:5527)
E/AndroidRuntime(31948): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31948): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
E/AndroidRuntime(31948): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
E/MQSEventManagerDelegate(31948): failed to get MQSService.
I/Process (31948): Sending signal. PID: 31948 SIG: 9

**Comment by aissamouajib** [comment]
@zarnimoehtet Hey man, I'm facing the same issue, did you find a way a solution to this problem?

**Comment by Sithira** [comment]
Has been updated to v2. Please check the master branch
