### ISSUE TITLE
audio title is not displayed with the screen locked

### ISSUE THREAD

**Issue by dprogrammer** [Sithira/FlutterRadioPlayer#33]
HI,

Config
await _flutterRadioPlayer.init("Flutter Radio Example", "Live", "URL_HERE", "true");

With the screen locked does not display "Flutter Radio Example" and "Live", after turning on the screen, display "unknown" and "unknown"

[https://imgur.com/a/sh8k9Ln](https://imgur.com/a/sh8k9Ln)

**Comment by maendamedia** [comment]
Still not working. Any news on this?

**Comment by Sithira** [comment]
Has been updated to v2. Please check the master branch
