### ISSUE TITLE
iOS: init 'playWhenReady' flag ignored 

### ISSUE THREAD

**Issue by agreensh** [Sithira/FlutterRadioPlayer#34]
You need to do this (so set to false by default, only set true if the string == "true")
In initService (StreamingCore.swift)
``` 
    self.playWhenReady = false

    if playWhenReady == "true" {
        print("PlayWhenReady: true")
        self.playWhenReady = true
    }
```

**Comment by JanStorm** [comment]
Seems fine for me. Initializing variable in line 18 with false (Like the first part in your code), then in line 41 its getting true when set so:
https://github.com/Sithira/FlutterRadioPlayer/blob/master/ios/Classes/core/StreamingCore.swift#L41 Just as you mentioned :)

**Comment by Sithira** [comment]
Has been updated to v2. Please check the master branch
