### ISSUE TITLE
Radio continues where it was paused instead of reinitializing a stream as an actual radio would do

### ISSUE THREAD

**Issue by ivancernja** [Sithira/FlutterRadioPlayer#36]
Even tried forking the repo to change the invoke method of pause() to stop() so playOrPause() becomes playOrStop()

**Comment by bafplus** [comment]
Im having the same issue. When it comes to live broadcasts its should simply stop without detaching itself, so when resumed it would start the stream at "live" current time. I havent tested it, but does thius also means it keeps buffering the stream when paused? If thats the case that would also result in a big storage if paused for a long time.

**Comment by Sithira** [comment]
Has been updated to v2. Please check the master branch
