### ISSUE TITLE
Null Safety Conversion

### ISSUE THREAD

**Issue by MuhammadFaizan980** [Sithira/FlutterRadioPlayer#44]
Hi!
Please release null safety version of this package
Thanks

**Comment by bafplus** [comment]
Totally agree!

**Comment by pishguy** [comment]
+1

**Comment by Sithira** [comment]
working on this

**Comment by FlawLessx** [comment]
Any update on this?

**Comment by dv336699** [comment]
@Sithira https://github.com/Sithira/FlutterRadioPlayer/pull/54 any chance this can be merged?

Thanks

**Comment by Sithira** [comment]
Kindly update to newest version
