### ISSUE TITLE
Navigation not working in example

### ISSUE THREAD

**Issue by bafplus** [Sithira/FlutterRadioPlayer#45]
The noob that i am is using the suplied example as boilerplate for my app.
Everything works fine.
Now i want to add 1 or 2 static text widgets/pages but i cant seem to get the navigation in the bottomNavigationBar working.
Can somebody take a look at that and maybe even get it to work?

I just cant wrap my head around why it isnt working, and the noobnes of me prevent me from fixing.

**Comment by Sithira** [comment]
Has been updated to v2. Please check the master branch
