### ISSUE TITLE
Problem with  SDK 30

### ISSUE THREAD

**Issue by leandregg** [Sithira/FlutterRadioPlayer#46]
Hello,
Now in PlayStore it is mandatory to upload an app with SDK 30.
This library gives an error when compiling in that version. 

Error log:

e: C:\Users\leand\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_radio_player-1.0.7\android\src\main\kotlin\me\sithiramunasinghe\flutter\flutter_radio_player\core\StreamingCore.kt: (121, 90): Type mismatch: inferred type is String? but String was expected
e: C:\Users\leand\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_radio_player-1.0.7\android\src\main\kotlin\me\sithiramunasinghe\flutter\flutter_radio_player\core\StreamingCore.kt: (123, 63): Type mismatch: inferred type is String? but String was expected
e: C:\Users\leand\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_radio_player-1.0.7\android\src\main\kotlin\me\sithiramunasinghe\flutter\flutter_radio_player\core\StreamingCore.kt: (174, 32): Type mismatch: inferred type is String? but String was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_radio_player:compileReleaseKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 19s

**Comment by Sithira** [comment]
Looking into this. Thank for the report

**Comment by NikiTsitsiroudi** [comment]
Any updates on that as I am facing the same issue and I am unable to build my app?

**Comment by ashishCodixel** [comment]
@Sithira please take an action on this issue as soon as possible.

**Comment by Sithira** [comment]
Has been updated to v2. Please check the master branch
