### ISSUE TITLE
Stream Issue When Listen in 2 Screen

### ISSUE THREAD

**Issue by yusriltakeuchi** [Sithira/FlutterRadioPlayer#49]
I have an issue with stream builder here.

I have two screens, that's is A and B.
i place StreamBuilder in the both of screen and listen to the same screen "_isPlayingStream" in Provider.

When i open screen B, i run the function Flutter radio init, and the stream running in screen A and B.

But when i close screen B, the stream in screen A not working, when i test print it's not receiving any stream data.

**Comment by maendamedia** [comment]
Did you get this solved? And if yes? How did you do that?
