### ISSUE TITLE
Crash on android

### ISSUE THREAD

**Issue by yusriltakeuchi** [Sithira/FlutterRadioPlayer#53]
My application going crash sometime when run in release mode, when i check in the crashlytics logs, the problem in this libary and say "Services not registered"

 Can you give me solution to handle this issue?
<img width="901" alt="Screen Shot 2021-09-09 at 12 58 34" src="https://user-images.githubusercontent.com/10339660/132631240-deda2c7c-2232-4403-b075-aa1af8abadc8.png">

**Comment by Sithira** [comment]
Kindly update to newest version
