### ISSUE TITLE
Null can not be a value of a non-null type AudioFocusRequest

### ISSUE THREAD

**Issue by dzero1** [Sithira/FlutterRadioPlayer#56]
Android Build faild with following error:

...../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_radio_player-1.1.0/android/src/main/kotlin/me/sithiramunasinghe/flutter/flutter_radio_player/core/StreamingCore.kt: (62, 51): Null can not be a value of a non-null type AudioFocusRequest

**Comment by Sithira** [comment]
Has been updated to v2. Please check the master branch
