### ISSUE TITLE
 Type mismatch: inferred type is AudioFocusRequest? but AudioFocusRequest was expected

### ISSUE THREAD

**Issue by StripedMittens** [Sithira/FlutterRadioPlayer#57]
.pub-cache\hosted\pub.dartlang.org\flutter_radio_player-1.1.0\android\src\main\kotlin\me\sithiramunasinghe\flutter\flutter_radio_player\core\StreamingCore.kt: (188, 46): Type mismatch: inferred type is AudioFocusRequest? but AudioFocusRequest was expected

**Comment by EnriqueMx** [comment]
Waiting for same fix here. Thanks

**Comment by ignaciomarti** [comment]
I'm facing same problem. Did you find any solution?

**Comment by feralink-fga** [comment]
> Waiting for same fix here. Thanks


waiting too. any prevision?

**Comment by shahryar-cmyk** [comment]
changing the android build.gradle dependencies will somehow resolve this issue. 
```
dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
```
also notices changes the not writing this also helps in-app module build.gradle. 

    <application android:usesCleartextTraffic="true">
        <service android:name=".core.StreamingCore"/>
    </application>

**Comment by feralink-fga** [comment]
**resolves compilation error but generates others**

app:processDebugResources FAILED
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings

**Comment by filippodicostanzo** [comment]
Same issue with

```
    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
```

how to resolve?

**Comment by buroz** [comment]
Any solution? Because I am also getting the same error.

**Comment by xrayDon** [comment]
Any solution, I have same issue here :Type mismatch: inferred type is AudioFocusRequest? but AudioFocusRequest was expected

**Comment by KaviHarjani** [comment]
In March, with same error

**Comment by Sithira** [comment]
Flutter radio 2.0.0 will be released soon. Stay tuned

**Comment by pjarnfelt** [comment]
In May and same error. What's ETA on 2.0.0?

**Comment by FlatCodeIq** [comment]
Same issue still

> Flutter radio 2.0.0



It's May 21st and no solution or work around is presented by your side. Please state a workaround at least or ETA for the new version and why would it fix this problem?

**Comment by KaviHarjani** [comment]
> o solution or work around is presented by your side. Please state a workaround at least or ETA for the new version and why would it fix this problem?

Hey you can try out audioplayers, they're good, I'm using them currently

**Comment by Sithira** [comment]
Has been updated to v2. Please check the master branch
