### ISSUE TITLE
[Crash] Service not registered and Apps Crash when open

### ISSUE THREAD

**Issue by yusriltakeuchi** [Sithira/FlutterRadioPlayer#60]
I want to report how my application crash after using this package.
The app crashes after i close and reopen again, but this only happened a few times.

This is log from Crashlytics
<img width="914" alt="Screen Shot 2021-12-08 at 13 37 17" src="https://user-images.githubusercontent.com/10339660/145160537-a83c041b-c79e-4fbd-b14d-72fe99b58490.png">

@Sithira maybe you can give me solution to solve this?

**Comment by Sithira** [comment]
Has been updated to v2. Please check the master branch
