### ISSUE TITLE
Unsupported type: 4 Error

### ISSUE THREAD

**Issue by yusriltakeuchi** [Sithira/FlutterRadioPlayer#62]
I got this error when try init player.

Unable to start service me.sithiramunasinghe.flutter.flutter_radio_player.core.StreamingCore@ced94ff with Intent { cmp=co.genpi.genpi/me.sithiramunasinghe.flutter.flutter_radio_player.core.StreamingCore (has extras) }: java.lang.IllegalStateException: Unsupported type: 4

I try with this stream radio url
https://n0e.radiojar.com/7csmg90fuqruv?rj-tok=AAABfi5ajaYAnTvcvZGQDWdZIg&rj-ttl=5

please help me @Sithira

**Comment by mikeb2k** [comment]
Bump, started to get the same error, no clue why, havent touched the radio code since it was working.

**Comment by yusriltakeuchi** [comment]
> Bump, started to get the same error, no clue why, havent touched the radio code since it was working.

You can try using my repository, this repo is support for Flutter 3.0.5. I'm doing a lot of modification to support in the latest flutter version.

```yaml
flutter_radio_player:
    git:
      url: https://github.com/yusriltakeuchi/FlutterRadioPlayer.git
```

**Comment by Sithira** [comment]
Has been updated to v2. Please check the master branch
