### ISSUE TITLE
FlutterRadioPlayer cant follow redirects

### ISSUE THREAD

**Issue by scysys** [Sithira/FlutterRadioPlayer#63]
Example stream url to play: http://example.com/stream

Redirects as an loadbalancer to 

- http://sub1.example.com/stream
- http://sub2.example.com/stream

Actually FlutterRadioPlayer cant handle the above play link. Only working when using the direct endpoint

**Comment by Sithira** [comment]
It will only support direct endpoints.

Has been updated to v2. Please check the master branch
