### ISSUE TITLE
Android standby display info, Artist & Title don't display correctly!

### ISSUE THREAD

**Issue by RadioActive913** [Sithira/FlutterRadioPlayer#65]
Hi there, I'm not a developer, but just a simple radio owner. I have this developer who's been trying to solve this problem for the last month or so and from what he says there has to be a bug in the library or something.
Here's a screen shot of the erroneous display showing on my developer's phone:
![bad_metadata](https://user-images.githubusercontent.com/99253325/170878279-597c146a-0a3b-44f0-82fb-d1cf0f305db5.jpg)
The artist here is "Cure" and the track title is "Lullaby", in this screen shot we see El Paso, who is an artist from a previous track (actually the first track when I run the app, the artist stays there on top and never changes!), and Cure - Lullaby is on the second line which, from what I understand the line for just the title, so I'm assuming that the Top Line with bolder characters is the artist and the Bottom line is for the title...
Clearly that doesn't happen in my case, and he swears to me that he's parsing the metadata correctly and also is trying to manually debug it, by entering data for artist and title separately and it still gets a messed up display:
![debug1](https://user-images.githubusercontent.com/99253325/170878627-2bf08cbe-a0fc-406f-ad63-7155c27b2b42.jpg)
param string subTitle not working, I put word LIVE

![debug2](https://user-images.githubusercontent.com/99253325/170878703-3a1ee2ed-ec08-4725-81a5-f2d35679d10f.jpg)
not show word LIVE

Any ideas, or help would be greatly appreciated!

**Comment by Sithira** [comment]
Has been updated to v2. Please check the master branch
