### ISSUE TITLE
FATAL EXCEPTION: Unsupported type 4

### ISSUE THREAD

**Issue by mikeb2k** [Sithira/FlutterRadioPlayer#67]
Hello, Ive just started to get this issue:  java.lang.IllegalStateException: Unsupported type: 4 
Full log - https://fastbin.codes/famalezaho.apache
Havent touched the radio code for a good while, last time everything was fine.

**Comment by mikeb2k** [comment]
Turns out having assets_audio_player present breaks this radio plugin.

**Comment by Sithira** [comment]
Has been updated to v2. Please check the master branch
