### ISSUE TITLE
Android 12 crash

### ISSUE THREAD

**Issue by armkir** [Sithira/FlutterRadioPlayer#69]
In android 12 device app crashing

E/AndroidRuntime( 3878): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
E/AndroidRuntime( 3878): 	at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
E/AndroidRuntime( 3878): 	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:673)
E/AndroidRuntime( 3878): 	at android.app.PendingIntent.getBroadcast(PendingIntent.java:660)
E/AndroidRuntime( 3878): 	at com.google.android.exoplayer2.ui.PlayerNotificationManager.createBroadcastIntent(PlayerNotificationManager.java:1395)
E/AndroidRuntime( 3878): 	at com.google.android.exoplayer2.ui.PlayerNotificationManager.createPlaybackActions(PlayerNotificationManager.java:1351)
E/AndroidRuntime( 3878): 	at com.google.android.exoplayer2.ui.PlayerNotificationManager.<init>(PlayerNotificationManager.java:658)
E/AndroidRuntime( 3878): 	at com.google.android.exoplayer2.ui.PlayerNotificationManager.<init>(PlayerNotificationManager.java:568)
E/AndroidRuntime( 3878): 	at com.google.android.exoplayer2.ui.PlayerNotificationManager.createWithNotificationChannel(PlayerNotificationManager.java:521)
E/AndroidRuntime( 3878): 	at me.sithiramunasinghe.flutter.flutter_radio_player.core.StreamingCore.onStartCommand(StreamingCore.kt:248)
E/AndroidRuntime( 3878): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5092)
E/AndroidRuntime( 3878): 	... 9 more
I/Process ( 3878): Sending signal. PID: 3878 SIG: 9
Lost connection to device.

**Comment by Sithira** [comment]
Has been updated to v2. Please check the master branch
