### ISSUE TITLE
Getting 'fatal error: Unexpectedly found nilwhile unwrapping an Optional value' in iOS at runtime

### ISSUE THREAD

**Issue by manojvsp12** [Sithira/FlutterRadioPlayer#7]
Error: 'fatal error: Unexpectedly found nil while unwrapping an Optional value: file /flutter_radio_player-1.0.4/ios/Classes/SwiftFlutterRadioPlayerPlugin.swift, line 100'

Flutter version: 1.18.0-6.0.pre.80 (master channel)

code in Flutter:
import 'package:flutter/material.dart';
import 'package:flutter_radio_player/flutter_radio_player.dart';
main() => runApp(RadioApp());
class RadioApp extends StatefulWidget {
  @override
  _RadioAppState createState() => _RadioAppState();
}

class _RadioAppState extends State<RadioApp> {
FlutterRadioPlayer _flutterRadioPlayer = new FlutterRadioPlayer();

String url = '<http url provided>';

@override
  void initState() {
    print('initializing');
    super.initState();
    audioStart();
}

Future<void> audioStart() async {
      await _flutterRadioPlayer.init(
          "Flutter Radio Example", "Live", url, "true");
}

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'SHOUT Radio',
        debugShowCheckedModeBanner: false,
        home: SafeArea(child: Scaffold()));
  }
}

**Comment by Sithira** [comment]
Hi,

Kindly follow the given example. The current version is working on iOS 10 - 13. If it crashes further send me the log from Xcode. I'm closing this now. You may reopen if required.

Thanks for trying out the plugin 👍

**Comment by maxbhoria** [comment]
> Error: 'fatal error: Unexpectedly found nil while unwrapping an Optional value: file /flutter_radio_player-1.0.4/ios/Classes/SwiftFlutterRadioPlayerPlugin.swift, line 100'
> 
> Flutter version: 1.18.0-6.0.pre.80 (master channel)
> 
> code in Flutter:
> import 'package:flutter/material.dart';
> import 'package:flutter_radio_player/flutter_radio_player.dart';
> main() => runApp(RadioApp());
> class RadioApp extends StatefulWidget {
> @override
> _RadioAppState createState() => _RadioAppState();
> }
> 
> class _RadioAppState extends State {
> FlutterRadioPlayer _flutterRadioPlayer = new FlutterRadioPlayer();
> 
> String url = '';
> 
> @override
> void initState() {
> print('initializing');
> super.initState();
> audioStart();
> }
> 
> Future audioStart() async {
> await _flutterRadioPlayer.init(
> "Flutter Radio Example", "Live", url, "true");
> }
> 
> @override
> Widget build(BuildContext context) {
> return MaterialApp(
> title: 'SHOUT Radio',
> debugShowCheckedModeBanner: false,
> home: SafeArea(child: Scaffold()));
> }
> }

Hello did you resolve this problem? If yes please update me as well how.

**Comment by hitesh-dhamshaniya** [comment]
Is there any solution for the issue, I am also facing the same issue... 

If there is a solution kindly share... Thank you.

**Error: 'fatal error: Unexpectedly found nil while unwrapping an Optional value: file /flutter_radio_player-1.0.4/ios/Classes/SwiftFlutterRadioPlayerPlugin.swift, line 100'**

@maxbhoria and @Sithira
