### ISSUE TITLE
Not resuming playback on Internet resume

### ISSUE THREAD

**Issue by deep1931** [Sithira/FlutterRadioPlayer#74]
Hello,

I have tested with internet events, when i switched off the internet it shows the flutter_radio_paused event, and on resume internet is turned into flutter_radio_loading and then nothing happened. Then on click of play button also nothing happened. 

Please help with internet events, player should play/pause as per connectivity conditions. 

Test project is the same library example.

Thanks

**Comment by Sithira** [comment]
which device did you test this on?

**Comment by Sithira** [comment]
v3.0.0 has been released with new features. make sure to check it out. if it does not fix your problem please feel free to reopen this issue
