### ISSUE TITLE
FRPCoreService has not been initialized yet

### ISSUE THREAD

**Issue by netmindz** [Sithira/FlutterRadioPlayer#81]
I have tried to take your example app, but I'm having issues where the play controls get out of sync.

For example, if i press stop,  then play i get the attached error
[log.txt](https://github.com/Sithira/FlutterRadioPlayer/files/11242360/log.txt)

**Comment by Sithira** [comment]
Can you check with the new update ?

**Comment by netmindz** [comment]
I might also try https://github.com/Sithira/FlutterRadioPlayer/pull/78 to see if the changes made to fix the initialization of the player resolves my issue

Also, did you see my PR for the compile error?

**Comment by netmindz** [comment]
The same issue remains with 2.0.2

**Comment by jorge-cuervo** [comment]
I have the same problem, when I hit stop it sends me an error

**Comment by Russsgithub** [comment]
@Sithira , relating to this issue.

It states in the readme
```
stop() - Will stop all the streaming audio streams and detaches itself from FOREGROUND SERVICE. You need to reinitialize to use the plugin again,
```

How do i do this.

I've tried using

```
widget.flutterRadioPlayer.initPlayer();
```

but have no luck , It looks as if the initialization is done at onCreate().

Any chance you could add to the readme to explain how to re-initialize the player after stop() has been called. I'm reluctant to use pause() and leave the player pulling data as users may leave this for potentially long periods before listening again.

Thanks for the library, it works well for me apart from this.

**Comment by Sithira** [comment]
v3.0.0 has been released with new features. make sure to check it out. if it does not fix your problem please feel free to reopen this issue
