### ISSUE TITLE
PlatformException on Release 

### ISSUE THREAD

**Issue by jsaravia36** [Sithira/FlutterRadioPlayer#82]
Help, please. My app works perfectly in debug mode. But when I try to build it for release I get these Platform Errors:

` [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(FRP_010, Failed to call set_sources, null, null)
E/flutter (11615): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652)
E/flutter (11615): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310)
E/flutter (11615): <asynchronous suspension>
E/flutter (11615): #2      FlutterRadioPlayer.addMediaSources (package:flutter_radio_player/flutter_radio_player.dart:60)
E/flutter (11615): <asynchronous suspension>
E/flutter (11615): 
E/flutter (11615): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(FRP_008, Failed to call prev_source, null, null)
E/flutter (11615): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652)
E/flutter (11615): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310)
E/flutter (11615): <asynchronous suspension>
E/flutter (11615): #2      FlutterRadioPlayer.seekToMediaSource (package:flutter_radio_player/flutter_radio_player.dart:91)
E/flutter (11615): <asynchronous suspension>`

**Comment by JanStorm** [comment]
I can reproduce this issue with the current example app provided in this repository. Just by doing `flutter run --release`

**Comment by kosmas1991** [comment]
Yeah, same issue here

**Comment by Sithira** [comment]
v3.0.0 has been released with new features. make sure to check it out. if it does not fix your problem please feel free to reopen this issue
