### ISSUE TITLE
java.lang.IllegalStateException: Handler (android.os.Handler)

### ISSUE THREAD

**Issue by fhenriqueo** [Sithira/FlutterRadioPlayer#83]
Hello, could you help me please?

The error below happens when the application is closed by Android (manually or by the system) and when returning/opening the app and clicking Play again, it no longer runs, as the error occurs.

When closing the app through the Android settings and opening it, it plays normally again.

Thanks!

`W/MessageQueue( 1390): Handler (android.os.Handler) {d27a75c} sending message to a Handler on a dead thread
W/MessageQueue( 1390): java.lang.IllegalStateException: Handler (android.os.Handler) {d27a75c} sending message to a Handler on a dead thread
W/MessageQueue( 1390): 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:567)
W/MessageQueue( 1390): 	at android.os.Handler.enqueueMessage(Handler.java:778)
W/MessageQueue( 1390): 	at android.os.Handler.sendMessageAtTime(Handler.java:727)
W/MessageQueue( 1390): 	at android.os.Handler.sendMessageDelayed(Handler.java:697)
W/MessageQueue( 1390): 	at android.os.Handler.sendMessage(Handler.java:635)
W/MessageQueue( 1390): 	at android.os.Message.sendToTarget(Message.java:469)
W/MessageQueue( 1390): 	at com.google.android.exoplayer2.util.SystemHandlerWrapper$SystemMessage.sendToTarget(SystemHandlerWrapper.java:155)
W/MessageQueue( 1390): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.setPlayWhenReady(ExoPlayerImplInternal.java:314)
W/MessageQueue( 1390): 	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlayWhenReady(ExoPlayerImpl.java:2622)
W/MessageQueue( 1390): 	at com.google.android.exoplayer2.ExoPlayerImpl.setPlayWhenReady(ExoPlayerImpl.java:767)
W/MessageQueue( 1390): 	at com.google.android.exoplayer2.BasePlayer.pause(BasePlayer.java:111)
W/MessageQueue( 1390): 	at me.sithiramunasinghe.flutter.flutter_radio_player.core.services.FRPCoreService.pause(FRPCoreService.kt:256)
W/MessageQueue( 1390): 	at me.sithiramunasinghe.flutter.flutter_radio_player.FlutterRadioPlayerPlugin.onMethodCall(FlutterRadioPlayerPlugin.kt:185)
W/MessageQueue( 1390): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
W/MessageQueue( 1390): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
W/MessageQueue( 1390): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
W/MessageQueue( 1390): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
W/MessageQueue( 1390): 	at android.os.Handler.handleCallback(Handler.java:938)
W/MessageQueue( 1390): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/MessageQueue( 1390): 	at android.os.Looper.loop(Looper.java:250)
W/MessageQueue( 1390): 	at android.app.ActivityThread.main(ActivityThread.java:7755)
W/MessageQueue( 1390): 	at java.lang.reflect.Method.invoke(Native Method)
W/MessageQueue( 1390): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
W/MessageQueue( 1390): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)`

**Comment by MoatazNoaman2001** [comment]
same as above, but when i rerun the app in debug mode its return to work!

**Comment by bossly** [comment]
Quick fix here: https://github.com/Sithira/FlutterRadioPlayer/pull/94

**Comment by Sithira** [comment]
v3.0.0 has been released with new features. make sure to check it out. if it does not fix your problem please feel free to reopen this issue
