### ISSUE TITLE
IOS error message

### ISSUE THREAD

**Issue by naxtertech** [Sithira/FlutterRadioPlayer#87]
I am getting this error message:

![Screenshot 2023-10-16 at 10 24 15 AM](https://github.com/Sithira/FlutterRadioPlayer/assets/117926282/dd107c8d-57bf-43d4-b1d5-39d14087dbaf)

**Comment by GrzegorzKastelik** [comment]
I have probably the same:

```
Swift Compiler Error (Xcode): Cannot convert value of type '(Array<AVMetadataItem>) -> ()' to expected argument type '(AudioPlayer.MetadataEventData) -> Void' (aka '(Array<AVTimedMetadataGroup>) -> ()')
/Users/builder/.pub-cache/hosted/pub.dev/flutter_radio_player-2.0.2/ios/Classes/core/services/FRPCoreService.swift:49:
```

**Comment by Sithira** [comment]
v3.0.0 has been released with new features. make sure to check it out. if it does not fix your problem please feel free to reopen this issue
