### ISSUE TITLE
 stop audio when receiving phone call

### ISSUE THREAD

**Issue by sauloemidio** [Sithira/FlutterRadioPlayer#9]
Hello, as when receiving a phone call, stop the audio!
Stop in the stream and return when the phone call ends?

**Comment by Sithira** [comment]
Hi,

It is. Let me know if it doesn't work.

**Comment by sauloemidio** [comment]
I verified that from version 8.0 api 26 the audio focus works when receiving a phone call, so it's not a problem!
 Now try to make it work in the later versions.
