### ISSUE TITLE
CarPlay support

### ISSUE THREAD

**Issue by maendamedia** [Sithira/FlutterRadioPlayer#90]
Does this module have CarPlay support?
Are in any way usable on carPlay?

**Comment by Sithira** [comment]
Flutter radio player supports Apple Car Play by default :-). No Additional configurations needed

**Comment by maendamedia** [comment]
In what way is it supported? IE what do i see i carplay?

**Comment by Sithira** [comment]
Station title, Album art (if provided) and now playing info (if your server supports it)
