### ISSUE TITLE
How to customize iOS control center metadatas ?

### ISSUE THREAD

**Issue by im-sacha-cohen** [Sithira/FlutterRadioPlayer#99]
Hey there,

How is it possible to display and customize artist, title and image metadatas on iOS control center like shown below ?

![IMG_1872](https://github.com/user-attachments/assets/9590c6bf-de17-4e53-abf6-d6ef58ccb5db)

Thanks

**Comment by Sithira** [comment]
Hi, In version 2.x.x, customisation is impossible for Album art. But If you checkout to branch development/v3 you can have that capability built in.

**Comment by Sithira** [comment]
@im-sacha-cohen new version (v3) was just released

**Comment by im-sacha-cohen** [comment]
Super !🙌
